/**
 * Blog URLs for sitemap.xml (web build must not import packages/database).
 * Keep in sync with `packages/database/prisma/data/blogs.ts` → blogSitemapEntries.
 */
export const blogSitemapEntries: { slug: string; publishedAt: string }[] = [
  { slug: "pawan-kalyan-complete-guide-2026", publishedAt: "2026-05-20" },
  { slug: "pawan-kalyan-age-birthday-biography", publishedAt: "2026-05-18" },
  { slug: "best-pawan-kalyan-movies-list", publishedAt: "2026-05-16" },
  { slug: "pawan-kalyan-dialogues-iconic-lines", publishedAt: "2026-05-14" },
  { slug: "pawan-kalyan-wallpapers-hd-4k-download", publishedAt: "2026-05-12" },
  { slug: "jana-sena-party-pawan-kalyan-janasenani", publishedAt: "2026-05-10" },
  { slug: "gabbar-singh-pawan-kalyan-blockbuster", publishedAt: "2026-05-08" },
  { slug: "attarintiki-daredi-pawan-kalyan", publishedAt: "2026-05-06" },
  { slug: "pawan-kalyan-latest-news-2026", publishedAt: "2026-05-04" },
  { slug: "bro-movie-pawan-kalyan-2023", publishedAt: "2026-05-02" },
  { slug: "jalsa-kushi-pawan-kalyan-classics", publishedAt: "2026-04-28" },
  { slug: "pspk-power-star-meaning-nickname", publishedAt: "2026-04-25" },
  { slug: "pawan-kalyan-deputy-cm-2026-update", publishedAt: "2026-04-22" },
  { slug: "pawan-kalyan-telugu-cinema-search-trends", publishedAt: "2026-04-18" },
  { slug: "pawan-kalyan-upcoming-movies-og-hhvm", publishedAt: "2026-04-15" },
  { slug: "they-call-him-og-pawan-kalyan-updates", publishedAt: "2025-05-10" },
  { slug: "hari-hara-veera-mallu-pawan-kalyan-period-film", publishedAt: "2025-04-28" },
  { slug: "pawan-kalyan-harvard-speech-power-star-global", publishedAt: "2025-03-22" },
  { slug: "jana-sena-2024-election-sweep-pawan-kalyan", publishedAt: "2025-02-14" },
  { slug: "bheemla-nayak-pawan-kalyan-blockbuster-legacy", publishedAt: "2025-01-20" },
  { slug: "vakeel-saab-pawan-kalyan-courtroom-legacy", publishedAt: "2024-12-05" },
  { slug: "pawan-kalyan-philanthropy-charity-foundation", publishedAt: "2024-11-18" },
  { slug: "power-star-pawan-kalyan-global-fan-phenomenon", publishedAt: "2024-10-30" },
  { slug: "deputy-cm-pawan-kalyan-rural-field-visits", publishedAt: "2024-10-08" },
  { slug: "pawan-kalyan-andhra-politics-2025-balanced-view", publishedAt: "2024-09-15" },
  { slug: "pawan-kalyan-deputy-cm-andhra-pradesh-role", publishedAt: "2025-03-15" },
  { slug: "pawan-kalyan-journey-cinema-to-deputy-cm", publishedAt: "2025-04-02" },
  { slug: "jal-jeevan-mission-andhra-pawan-kalyan", publishedAt: "2025-05-10" },
  { slug: "panchayat-raj-rural-development-pawan-kalyan", publishedAt: "2025-06-01" },
  { slug: "nda-alliance-andhra-pradesh-pawan-kalyan-2024", publishedAt: "2025-06-18" },
  { slug: "environment-forest-portfolio-pawan-kalyan", publishedAt: "2025-07-05" },
  { slug: "mgnregs-rural-livelihoods-pawan-kalyan", publishedAt: "2025-08-12" },
  { slug: "pawan-kalyan-different-kind-of-leader", publishedAt: "2025-09-01" },
  { slug: "deputy-cm-pawan-kalyan-first-year-highlights", publishedAt: "2025-10-20" },
  { slug: "jana-sena-andhra-development-agenda-road-ahead", publishedAt: "2025-11-08" },
];
